# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='horario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='horarioFin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='horarioIni',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comida',
            name='descripcion',
            field=models.CharField(default='descripcion del producot', max_length=500),
        ),
        migrations.AlterField(
            model_name='comida',
            name='imagen',
            field=models.ImageField(upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='formasDePago',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Efectivo'), (1, 'Tarjeta de Crédito'), (2, 'Tarjeta de Débito'), (3, 'Tarjeta Junaeb')], max_length=7, null=True),
        ),
    ]
