# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170525_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='formasDePago',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Efectivo'), (1, 'Tarjeta de Crédito'), (2, 'Tarjeta de Débito'), (3, 'Tarjeta Junaeb')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='horarioFin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='horarioIni',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
