# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170525_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('idAlumno', models.IntegerField(primary_key=True, serialize=False)),
                ('idVendedor', models.IntegerField()),
            ],
            options={
                'db_table': 'Favoritos',
            },
        ),
        migrations.AlterField(
            model_name='comida',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
