# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170526_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritos',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favoritos',
            name='idAlumno',
            field=models.IntegerField(),
        ),
    ]
