# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_transacciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='fecha',
            field=models.CharField(default='<function', max_length=200),
        ),
    ]
