# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170529_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='fecha',
            field=models.CharField(default='2017-05-29', max_length=200),
        ),
    ]
